plugins {
    id 'java-library'
    id 'eclipse'
    id 'net.neoforged.moddev' version '1.0.21' // 1.21+ 전용 플러그인
}

version = '1.1'
group = 'com.yourname.modid'
base {
    archivesName = 'CrimsonSteveApi'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.65'

    runs {
        client {
            client()
        }

        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
    }

    mods {
        crimsonsteveapi { // ModId로 수정
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}